package cosc310_T28_librarySystem;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Objects;
import java.util.Scanner;

/**
 * 
 * @author Team 28
 * 
 *         The Account class is the subclass for User and Manager. Any activity
 *         both library users and library managers can do, such as searching a
 *         book, is implemented by this class.
 */
public class Account implements Serializable {
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private String userName, password;
    private int type;

    public Account() {

    }

    public Account(String userName, String password, int type) {
	super();
	this.userName = userName;
	this.password = password;
	this.type = type;
    }

    public String getUsername() {
	return userName;
    }

    public boolean passwordEquals(String passwordEntered) {
	return password.equals(passwordEntered);
    }

    /**
     * Lists books which matches a search (if selectOneBook is false), or lists
     * books which matches a search and returns a single book (if selectOneBook is
     * true). Returning a single book is useful for checking out a book, etc.
     * 
     * @param scanner
     * @param localLibraryData
     * @param selectOneBook
     * @return
     */

	 //Search a book in the library, manager and user can all use this function. return a list of book that meet the requirements of user input
    ArrayList<Book> searchForABook(Scanner scanner, LocalLibraryData localLibraryData, boolean selectOneBook) {
	System.out.print("Enter all or part of the title: ");
	if (!scanner.hasNextLine()) {
	    return null;
	}
	String titleFragment = scanner.nextLine();

	System.out.println("Books found:");

	int numberFound = 0;
	Book bookFound = null;
	ArrayList<Book> bookFoundlist = new ArrayList<>();
	int i=1;
	for (Book book : localLibraryData.bookList) {
	    if (book.title.contains(titleFragment)) {
		System.out.println(i+": "+book.title + " ISBN: " + book.iSBN);
		bookFound = book;
		bookFoundlist.add(bookFound);
		i++;
		numberFound++;
	    }
	}
	if (numberFound == 0) {
	    System.out.println("Book not found.");
		return null;
	} 
	else{
	return bookFoundlist;
	}
	
    }

    /**
     * generated by Eclipse
     */
    @Override
    public boolean equals(Object obj) {
	if (this == obj)
	    return true;
	if (obj == null)
	    return false;
	if (getClass() != obj.getClass())
	    return false;
	Account other = (Account) obj;
	return Objects.equals(password, other.password) && type == other.type
		&& Objects.equals(userName, other.userName);
    }

}
