package cosc310_T28_librarySystem;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.Objects;

/**
 * 
 * @author Team 28
 * 
 *         Each Book object stores the information about one book, and has no
 *         methods.
 */
public class Book implements Serializable {
    BookGroup bg;
    long iSBN;
    LocalDate date;
    int id;
    String title, author, cate;
    User holder = null;
    boolean borrow = false;

    public Book() {

    }

    public Book(BookGroup bg, long iSBN, LocalDate date, int id, String name, String author, String cate,
	    boolean borrow) {
	super();
	this.bg = bg;
	this.iSBN = iSBN;
	this.date = date;
	this.id = id;
	this.title = name;
	this.author = author;
	this.cate = cate;
	this.borrow = borrow;
    }

    /**
     * generated by Eclipse
     */
    @Override
    public boolean equals(Object obj) {
	if (this == obj)
	    return true;
	if (obj == null)
	    return false;
	if (getClass() != obj.getClass())
	    return false;
	Book other = (Book) obj;
	return Objects.equals(author, other.author) && Objects.equals(bg, other.bg) && borrow == other.borrow
		&& Objects.equals(cate, other.cate) && Objects.equals(date, other.date)
		&& iSBN == other.iSBN && id == other.id && Objects.equals(title, other.title);
    }

}
