package cosc310_T28_librarySystem;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Objects;

/**
 * 
 * @author Team 28
 * 
 *         Each BookGroup object is a subcategory which stores related books
 *         e.g. multiple volumes, and has no methods.
 *
 */
public class BookGroup implements Serializable {

    private int ISBN, date, num;
    private String name, author, cate;
    // private boolean borrow[];
    private Book books[];

    public BookGroup() {

    }

    public BookGroup(int ISBN, int date, int num, String name, String author, String cate) {
	super();
	this.ISBN = ISBN;
	this.date = date;
	this.num = num;
	this.name = name;
	this.author = author;
	this.cate = cate;
	books = new Book[num];
    }

    public String getTitle() {
	return name;
    }

    /**
     * generated by Eclipse
     */
    @Override
    public boolean equals(Object obj) {
	if (this == obj)
	    return true;
	if (obj == null)
	    return false;
	if (getClass() != obj.getClass())
	    return false;
	BookGroup other = (BookGroup) obj;
	return ISBN == other.ISBN && Objects.equals(author, other.author) && Arrays.equals(books, other.books)
		&& Objects.equals(cate, other.cate) && date == other.date && Objects.equals(name, other.name)
		&& num == other.num;
    }
}
